# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
      - image: selenium/hub:3.141.59-iron
      - image: selenium/node-chrome:3.141.59-iron
        environment:
          - HUB_HOST: localhost
      - image: selenium/node-firefox:3.141.59-iron
        environment:
          - HUB_HOST: localhost
          - NODE_PORT: 5556

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: waiting selenium grid to start
          command: |
            while ! curl -sSL "http://localhost:4444/wd/hub/status" 2>&1 \
                    | jq -r '.value.ready' 2>&1 | grep "true" >/dev/null; do
                echo 'Waiting for the Grid'
                sleep 1
            done
            >&2 echo "Selenium Grid is up"

      # run tests!
      - run: yarn test